require: standard

AllCops:
  SuggestExtensions: false
  Exclude:
    - "**/db/schema.rb"
    - "db/**/**"
    - "bin/**"
    - "vendor/**/*"

inherit_gem:
  standard: config/base.yml

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true
